FROM node:22-alpine AS build
WORKDIR /app

ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_PUBLISHABLE_KEY
ARG VITE_MARKETING_ORIGIN
ARG VITE_MARKETING_WWW_ORIGIN
ARG VITE_APP_ORIGIN
ARG VITE_ADMIN_ORIGIN
ARG VITE_DEMO_ORIGIN
ARG VITE_TEST_ORIGIN
ARG VITE_API_ORIGIN
ARG VITE_DOCS_ORIGIN

ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL \
    VITE_SUPABASE_PUBLISHABLE_KEY=$VITE_SUPABASE_PUBLISHABLE_KEY \
    VITE_MARKETING_ORIGIN=$VITE_MARKETING_ORIGIN \
    VITE_MARKETING_WWW_ORIGIN=$VITE_MARKETING_WWW_ORIGIN \
    VITE_APP_ORIGIN=$VITE_APP_ORIGIN \
    VITE_ADMIN_ORIGIN=$VITE_ADMIN_ORIGIN \
    VITE_DEMO_ORIGIN=$VITE_DEMO_ORIGIN \
    VITE_TEST_ORIGIN=$VITE_TEST_ORIGIN \
    VITE_API_ORIGIN=$VITE_API_ORIGIN \
    VITE_DOCS_ORIGIN=$VITE_DOCS_ORIGIN

COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:22-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production PORT=3000 HOST=0.0.0.0
COPY --from=build /app/.output ./.output
USER node
EXPOSE 3000
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD wget -qO- http://127.0.0.1:3000/healthz || exit 1
CMD ["node", ".output/server/index.mjs"]
