/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppRoosterRouteImport } from './routes/app.rooster'
import { Route as AppCijfersRouteImport } from './routes/app.cijfers'
import { Route as AppBerichtenRouteImport } from './routes/app.berichten'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRoosterRoute = AppRoosterRouteImport.update({
  id: '/rooster',
  path: '/rooster',
  getParentRoute: () => AppRoute,
} as any)
const AppCijfersRoute = AppCijfersRouteImport.update({
  id: '/cijfers',
  path: '/cijfers',
  getParentRoute: () => AppRoute,
} as any)
const AppBerichtenRoute = AppBerichtenRouteImport.update({
  id: '/berichten',
  path: '/berichten',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/berichten': typeof AppBerichtenRoute
  '/app/cijfers': typeof AppCijfersRoute
  '/app/rooster': typeof AppRoosterRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/berichten': typeof AppBerichtenRoute
  '/app/cijfers': typeof AppCijfersRoute
  '/app/rooster': typeof AppRoosterRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/berichten': typeof AppBerichtenRoute
  '/app/cijfers': typeof AppCijfersRoute
  '/app/rooster': typeof AppRoosterRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/berichten'
    | '/app/cijfers'
    | '/app/rooster'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app/berichten' | '/app/cijfers' | '/app/rooster' | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/berichten'
    | '/app/cijfers'
    | '/app/rooster'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rooster': {
      id: '/app/rooster'
      path: '/rooster'
      fullPath: '/app/rooster'
      preLoaderRoute: typeof AppRoosterRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cijfers': {
      id: '/app/cijfers'
      path: '/cijfers'
      fullPath: '/app/cijfers'
      preLoaderRoute: typeof AppCijfersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/berichten': {
      id: '/app/berichten'
      path: '/berichten'
      fullPath: '/app/berichten'
      preLoaderRoute: typeof AppBerichtenRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBerichtenRoute: typeof AppBerichtenRoute
  AppCijfersRoute: typeof AppCijfersRoute
  AppRoosterRoute: typeof AppRoosterRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBerichtenRoute: AppBerichtenRoute,
  AppCijfersRoute: AppCijfersRoute,
  AppRoosterRoute: AppRoosterRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
